# 28/01/2020

# NUMPY
- Numerical python
- why?
- creating numpy arrays
- attributes
- subsetting,slicing,indexing
- Array Manipulation
- Vectorize function
- Mathematical operations,broadcasting
- statistical functions,Trignometric functions,Logarithmic functions
- Linear algebra funcions
- Reading image data into numpy array
- Reading sklearn datasets as numpy array

In [1]:
import numpy

In [2]:
numpy.array([1,2,3])

array([1, 2, 3])

In [3]:
import numpy as np
np.__version__

'1.15.4'

In [5]:
from numpy import array
array([1,2,3,4])

array([1, 2, 3, 4])

In [6]:
from numpy import * # all the modules and subpackages will be imported

Numpy array creation from
- list
- tuple
- range

In [7]:
np.array([23,45,67])

array([23, 45, 67])

In [8]:
np.array((1,2,3))

array([1, 2, 3])

In [9]:
np.array(range(5,10))

array([5, 6, 7, 8, 9])

In [12]:
a=np.array(range(5,10))
print(a)
print(type(a))

[5 6 7 8 9]
<class 'numpy.ndarray'>


In [19]:
print(a.shape) # tuple
print(a.dtype) # data type
print(a.size) # no of elements
print(a.itemsize) # no of bytes for each items
print(a.ndim) # no of dimensions
print(a.nbytes) # total array size in bytes a.size*a.itemsize

(5,)
int32
5
4
1
20


In [17]:
l=[1]
t=(1,)
print(type(l),type(t))

<class 'list'> <class 'tuple'>


In [25]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
print(a2.dtype) 
print(a2.size) 
print(a2.itemsize) 
print(a2.ndim)
print(a2.nbytes)
print(a2.shape)

int32
9
4
2
36
(3, 3)


In [29]:
print(a2.shape[1])

3


In [33]:
a3=(((1,2,3),(4,5,6)))
a3

((1, 2, 3), (4, 5, 6))

In [31]:
help(np.array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K'

In [38]:
a4=np.array([1,2,3,4,312],dtype=np.int8)
print(a4.dtype) 
print(a4.size) 
print(a4.itemsize) 
print(a4.ndim)
print(a4.nbytes)
print(a4.shape)
a4


int8
5
1
1
5
(5,)


array([ 1,  2,  3,  4, 56], dtype=int8)

In [39]:
a5=np.array([1,2,3,7,(2**32)+1])
print(a5.dtype)

int64


In [48]:
a6=np.array([1,'jyo',42.5])
print(a6.dtype)

<U11


In [47]:
a7=np.array([1,2,3,4,None])
print(a7.dtype)
print(type(a[0]))

object
<class 'numpy.int32'>


In [46]:
a8=np.array([1,2,3,4,np.nan])
print(a8.dtype)

float64


In [49]:
help(np.ones)

Help on function ones in module numpy.core.numeric:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
   

In [51]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [52]:
np.ones((2,3),bool)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [54]:
np.ones(2,3,bool)

TypeError: data type not understood

Intializing arrays
- zeros
- ones
- full
- eye
- diag

In [58]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [59]:
help(np.full)

Help on function full in module numpy.core.numeric:

full(shape, fill_value, dtype=None, order='C')
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, `None`, means
         `np.array(fill_value).dtype`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of `fill_value` with the given shape, dtype, and order.
    
    See Also
    --------
    full_like : Return a new array with shape of input filled with value.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    zeros : Return a new array se

In [65]:
np.full((3,4),'jyo')

array([['jyo', 'jyo', 'jyo', 'jyo'],
       ['jyo', 'jyo', 'jyo', 'jyo'],
       ['jyo', 'jyo', 'jyo', 'jyo']], dtype='<U3')

In [67]:
help(np.eye)

Help on function eye in module numpy.lib.twodim_base:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    
    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.
    
  

In [71]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [72]:
np.eye(5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [76]:
help(np.diag)

Help on function diag in module numpy.lib.twodim_base:

diag(v, k=0)
    Extract a diagonal or construct a diagonal array.
    
    See the more detailed documentation for ``numpy.diagonal`` if you use this
    function to extract a diagonal and wish to write to the resulting array;
    whether it returns a copy or a view depends on what version of numpy you
    are using.
    
    Parameters
    ----------
    v : array_like
        If `v` is a 2-D array, return a copy of its `k`-th diagonal.
        If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
        diagonal.
    k : int, optional
        Diagonal in question. The default is 0. Use `k>0` for diagonals
        above the main diagonal, and `k<0` for diagonals below the main
        diagonal.
    
    Returns
    -------
    out : ndarray
        The extracted diagonal or constructed diagonal array.
    
    See Also
    --------
    diagonal : Return specified diagonals.
    diagflat : Create a 2-D array with the 

In [6]:
p=np.arange(9).reshape((3,3))
p

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.diag([2,3,4])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

creating arrays in a range
- arange
- linscape

In [77]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [78]:
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [79]:
np.arange(5,10,0.5)

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [81]:
help(linspace)

Help on function linspace in module numpy.core.function_base:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    Parameters
    ----------
    start : scalar
        The starting value of the sequence.
    stop : scalar
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    retstep : bo

[]-both are inclusive
[)
(]
()

In [4]:
np.linspace(5,10,10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [5]:
np.linspace(5,10,5,10)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [8]:
a=np.arange(5)
b=np.ones(5)
print(a)
print(b)

[0 1 2 3 4]
[1. 1. 1. 1. 1.]


In [9]:
# element wise
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a//b)

[1. 2. 3. 4. 5.]
[-1.  0.  1.  2.  3.]
[0. 1. 2. 3. 4.]
[0. 1. 2. 3. 4.]
[0. 0. 0. 0. 0.]
[-0.  1.  2.  3.  4.]


In [10]:
print(a**2)
print(a*2)
print(a+2)
print(a-2)
print(a/2)

[ 0  1  4  9 16]
[0 2 4 6 8]
[2 3 4 5 6]
[-2 -1  0  1  2]
[0.  0.5 1.  1.5 2. ]


### Random

In [26]:
np.random.randint(100)

88

In [ ]:
help(random.randint)

In [20]:
np.random.randint(100,size=3)

array([82, 60, 22])

In [21]:
np.random.randint(100,size=10)

array([78,  0, 34, 77, 10, 14, 53, 27, 92,  9])

In [22]:
np.random.randint(100,size=(4,2))

array([[22,  1],
       [31, 48],
       [39, 22],
       [79, 90]])

In [24]:
np.random.randint(100,size=(2,5))

array([[81, 23, 50,  2, 86],
       [16, 60, 69, 48, 45]])

In [25]:
np.random.randint(100,200,size=3)

array([141, 134, 195])

In [27]:
np.random.random()

0.6992107320383941

In [28]:
help(np.random.random)

Help on built-in function random_sample:

random_sample(...) method of mtrand.RandomState instance
    random_sample(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0).
    
    Results are from the "continuous uniform" distribution over the
    stated interval.  To sample :math:`Unif[a, b), b > a` multiply
    the output of `random_sample` by `(b-a)` and add `a`::
    
      (b - a) * random_sample() + a
    
    Parameters
    ----------
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    
    Returns
    -------
    out : float or ndarray of floats
        Array of random floats of shape `size` (unless ``size=None``, in which
        case a single float is returned).
    
    Examples
    --------
    >>> np.random.random_sample()
    0.47108547995356098
    >>> type(np.random.random_

In [29]:
np.random.random(10)

array([0.40109536, 0.08955035, 0.49418743, 0.44451822, 0.50937055,
       0.09784192, 0.04467879, 0.10299978, 0.1477428 , 0.58865871])

In [30]:
np.random.random((2,3))

array([[0.13600742, 0.46751048, 0.85447986],
       [0.21939517, 0.19547013, 0.71325248]])

In [31]:
np.random.rand()

0.7946766767688794

In [32]:
help(np.random.rand)

Help on built-in function rand:

rand(...) method of mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, should all be positive.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Notes
    -----
    This is a convenience function. If you want an interface that
    takes a shape-tuple as the first argument, refer to
    np.random.random_sample .
    
    Examples
    --------
    >>> np.random.rand(3,2)
    array([[ 0.14022471,  0.96360618],  #random
           [ 0.37601032,  0.25528411],  #random
           [ 0.49313049,  0.94909878]]

In [33]:
np.random.rand(3)

array([0.60069419, 0.8481509 , 0.42602956])

In [34]:
np.random.rand(2,5)

array([[0.35026416, 0.11015927, 0.37443923, 0.59636538, 0.61048105],
       [0.72650518, 0.79569624, 0.55599138, 0.48138205, 0.09870547]])

In [35]:
np.random.random((2,5))

array([[0.52449493, 0.61702338, 0.53184857, 0.1247582 , 0.73120918],
       [0.80659049, 0.59956281, 0.42737655, 0.15797766, 0.11591932]])

In [37]:
dir(np.random)

['Lock',
 'RandomState',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'absolute_import',
 'beta',
 'binomial',
 'bytes',
 'chisquare',
 'choice',
 'dirichlet',
 'division',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'info',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'np',
 'operator',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'standard_gamma',
 'standard_normal',
 'standard_t',
 'test',
 'triangular',
 'uniform',
 'vonmises',
 'wald',
 'warnings',
 'weibull',
 'zipf']

In [38]:
help(np.random.shuffle)

Help on built-in function shuffle:

shuffle(...) method of mtrand.RandomState instance
    shuffle(x)
    
    Modify a sequence in-place by shuffling its contents.
    
    This function only shuffles the array along the first axis of a
    multi-dimensional array. The order of sub-arrays is changed but
    their contents remains the same.
    
    Parameters
    ----------
    x : array_like
        The array or list to be shuffled.
    
    Returns
    -------
    None
    
    Examples
    --------
    >>> arr = np.arange(10)
    >>> np.random.shuffle(arr)
    >>> arr
    [1 7 5 2 9 4 3 6 0 8]
    
    Multi-dimensional arrays are only shuffled along the first axis:
    
    >>> arr = np.arange(9).reshape((3, 3))
    >>> np.random.shuffle(arr)
    >>> arr
    array([[3, 4, 5],
           [6, 7, 8],
           [0, 1, 2]])



In [39]:
r=np.arange(10,20)
np.random.shuffle(r)
print(r)

[17 11 14 12 19 10 15 16 13 18]


### Array Manipulation
- np.arange
- np.flatten
- np.expnad_dims
- np.reshape
- np.resize

In [40]:
a=np.arange(20)
a.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [41]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [45]:
a.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [46]:
a.reshape(10,5)

ValueError: cannot reshape array of size 20 into shape (10,5)

In [47]:
a.reshape(20,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [48]:
a.reshape(1,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [49]:
help(np.resize)

Help on function resize in module numpy.core.fromnumeric:

resize(a, new_shape)
    Return a new array with the specified shape.
    
    If the new array is larger than the original array, then the new
    array is filled with repeated copies of `a`.  Note that this behavior
    is different from a.resize(new_shape) which fills with zeros instead
    of repeated copies of `a`.
    
    Parameters
    ----------
    a : array_like
        Array to be resized.
    
    new_shape : int or tuple of int
        Shape of resized array.
    
    Returns
    -------
    reshaped_array : ndarray
        The new array is formed from the data in the old array, repeated
        if necessary to fill out the required number of elements.  The
        data are repeated in the order that they are stored in memory.
    
    See Also
    --------
    ndarray.resize : resize an array in-place.
    
    Examples
    --------
    >>> a=np.array([[0,1],[2,3]])
    >>> np.resize(a,(2,3))
    array([[0, 1, 2]

In [51]:
np.resize(a,(6,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [55]:
z=np.arange(20)
z.resize((13,2))
z

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [ 0,  0],
       [ 0,  0],
       [ 0,  0]])

In [56]:
np.expand_dims(a,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [57]:
np.expand_dims(a,0)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [59]:
a2=np.arange(10).reshape(2,5)
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [60]:
np.expand_dims(a2,1)

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [62]:
np.expand_dims(a2,0)

array([[[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]])

In [63]:
np.expand_dims(a2,1).shape

(2, 1, 5)

In [64]:
a2.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.expand_dims(a2,0).flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Iteration over 1d,2d,3d Arrays

In [67]:
for i in a:
    print(i)
    break

0


In [68]:
for i in a2:
    print(i)
    break

[0 1 2 3 4]


In [69]:
for i in np.arange(12).reshape(2,2,3):
    print(i)
    break

[[0 1 2]
 [3 4 5]]


In [71]:
np.arange(12).reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

### Indexing,slicing,subsetting

In [72]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [73]:
print(a[0])
print(a[-1])

0
19


In [74]:
print(a[2:10])
print(a[2:12:3])

[2 3 4 5 6 7 8 9]
[ 2  5  8 11]


In [75]:
print(a[[1,10,3]])

[ 1 10  3]


### fancy indexing

In [76]:
a%2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [77]:
a[a%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [78]:
a[[True,False]]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 20 but corresponding boolean dimension is 2

In [79]:
a[[ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False]]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [81]:
a2=np.arange(20).reshape(5,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [82]:
a2[0]

array([0, 1, 2, 3])

In [83]:
a2[-1]

array([16, 17, 18, 19])

In [84]:
a2[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
# reverse 
a2[[4,3,2,1,0]]

array([[16, 17, 18, 19],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [88]:
# prints 1,4,5 rows
a2[[True,False,False,True,True]]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [89]:
a2[2,2]

10

- rows-0,1,2,3,4
- colums-0,1,2,3

In [91]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [92]:
print(a2[2,2])
print(a2[2][2])

10
10


In [93]:
a2[3,3]

15

In [94]:
a2[1:4,2:4]

array([[ 6,  7],
       [10, 11],
       [14, 15]])

In [97]:
a2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [96]:
a2[3:5,2:4]

array([[14, 15],
       [18, 19]])

In [99]:
a2[[1,3,2],[3,2,1]]#(1,3),(3,2),(2,1)

array([ 7, 14,  9])