# 29/01/2020

## NUMPY-Time Comparision

In [1]:
import time
import numpy as np
start=time.time()
l=[x*x for x in range(100000)]
end=time.time()
print('time with lists: ',end-start)
start=time.time()
a=np.arange(100000)
a=a*a
end=time.time()
print('time with np arrays: ',end-start)

time with lists:  0.024965286254882812
time with np arrays:  0.0009703636169433594


### Trignometric functions

In [2]:
a=np.random.randint(100,size=23)
np.sin(a)


array([ 0.82682868,  0.96379539, -0.96139749, -0.40403765, -0.91652155,
       -0.00885131, -0.75098725,  0.63673801, -0.17607562,  0.39592515,
        0.96836446, -0.95375265,  0.0353983 , -0.89792768, -0.13235175,
       -0.53657292, -0.85551998,  0.98662759,  0.55142668, -0.99388865,
       -0.24525199, -0.94828214,  0.96379539])

In [3]:
np.sin(3.14/2)

0.9999996829318346

In [5]:
np.arcsin(1)

1.5707963267948966

In [7]:
np.rad2deg(1.5707963267948966)

90.0

In [8]:
np.deg2rad(90)

1.5707963267948966

In [11]:
import math
math.sin(a)

TypeError: only size-1 arrays can be converted to Python scalars

In [12]:
math.sin([2,3])

TypeError: must be real number, not list

### Log and Exponential functions

In [13]:
print(np.log(2))
print(np.log(1))
print(np.log(np.exp(1)))

0.6931471805599453
0.0
1.0


In [15]:
print(np.log2(2))
print(np.log2(32))

1.0
5.0


In [16]:
np.log(0)

C:\Users\DELL\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [17]:
np.exp(10)

22026.465794806718

In [20]:
np.log1p(2)
#np.log(x)=np.log(1+x)

1.0986122886681098

In [21]:
np.log1p(2+1)

1.3862943611198906

In [22]:
print(np.exp(1))

2.718281828459045


In [23]:
print(np.exp2(2))

4.0


In [24]:
print(np.expm1(5))
print(np.exp(5)-1)

147.4131591025766
147.4131591025766


### Statistics

In [25]:
a=np.random.randint(100,size=5)
a

array([42, 92, 23, 19,  5])

In [27]:
print(a.sum())
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))

181
181
36.2
23.0
30.301155093494376


In [28]:
print(np.quantile(a,0.25))
print(np.quantile(a,0.5))
print(np.quantile(a,0.75))

19.0
23.0
42.0


In [29]:
np.sort(a)

array([ 5, 19, 23, 42, 92])

### BroadCasting

In [33]:
a=np.arange(5)
b=np.arange(4)
a+b

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [34]:
a=np.arange(5)
b=np.arange(5)
a+b

array([0, 2, 4, 6, 8])

In [35]:
a=np.arange(10).reshape(5,2)
b=np.arange(2)
a+b

array([[ 0,  2],
       [ 2,  4],
       [ 4,  6],
       [ 6,  8],
       [ 8, 10]])

In [36]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [37]:
b

array([0, 1])

In [38]:
a=np.arange(10).reshape(5,2)
b=np.arange(5)
a+b

ValueError: operands could not be broadcast together with shapes (5,2) (5,) 

In [43]:
x=np.arange(15).reshape(3,5,1) # if ending one is present then it will take any number otherwise it take last number value
y=np.arange(5)
x+y

array([[[ 0,  1,  2,  3,  4],
        [ 1,  2,  3,  4,  5],
        [ 2,  3,  4,  5,  6],
        [ 3,  4,  5,  6,  7],
        [ 4,  5,  6,  7,  8]],

       [[ 5,  6,  7,  8,  9],
        [ 6,  7,  8,  9, 10],
        [ 7,  8,  9, 10, 11],
        [ 8,  9, 10, 11, 12],
        [ 9, 10, 11, 12, 13]],

       [[10, 11, 12, 13, 14],
        [11, 12, 13, 14, 15],
        [12, 13, 14, 15, 16],
        [13, 14, 15, 16, 17],
        [14, 15, 16, 17, 18]]])

In [42]:
x=np.arange(15).reshape(3,5,1)
y=np.arange(7)
x+y

array([[[ 0,  1,  2,  3,  4,  5,  6],
        [ 1,  2,  3,  4,  5,  6,  7],
        [ 2,  3,  4,  5,  6,  7,  8],
        [ 3,  4,  5,  6,  7,  8,  9],
        [ 4,  5,  6,  7,  8,  9, 10]],

       [[ 5,  6,  7,  8,  9, 10, 11],
        [ 6,  7,  8,  9, 10, 11, 12],
        [ 7,  8,  9, 10, 11, 12, 13],
        [ 8,  9, 10, 11, 12, 13, 14],
        [ 9, 10, 11, 12, 13, 14, 15]],

       [[10, 11, 12, 13, 14, 15, 16],
        [11, 12, 13, 14, 15, 16, 17],
        [12, 13, 14, 15, 16, 17, 18],
        [13, 14, 15, 16, 17, 18, 19],
        [14, 15, 16, 17, 18, 19, 20]]])

In [44]:
a=np.arange(15).reshape(5,3)
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

105
[30 35 40]
[ 3 12 21 30 39]


In [47]:
np.random.seed(5)
a=np.random.randint(50,size=10)
b=np.random.randint(50,size=10)
print(a)
print(b)

[35 14 47 38 16  9  8 36 39 27]
[48 30 16  7 12 15 49 39 16 27]


In [46]:
help(np.random.seed)

Help on built-in function seed:

seed(...) method of mtrand.RandomState instance
    seed(seed=None)
    
    Seed the generator.
    
    This method is called when `RandomState` is initialized. It can be
    called again to re-seed the generator. For details, see `RandomState`.
    
    Parameters
    ----------
    seed : int or 1-d array_like, optional
        Seed for `RandomState`.
        Must be convertible to 32 bit unsigned integers.
    
    See Also
    --------
    RandomState



In [48]:
def maxnumber(n1,n2):
    if n1>n2:
        return n1
    else:
        return n2
maxnumber(5,44)

44

In [49]:
maxnumber_vec=np.vectorize(maxnumber)
maxnumber_vec(a,b)

array([48, 30, 47, 38, 16, 15, 49, 39, 39, 27])

### Stacking

In [53]:
a=np.arange(6)
b=np.arange(6)
np.hstack([a,b])# no of rows should equal

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])

In [54]:
np.vstack([a,b])# no of columns should equal

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [55]:
a=np.arange(6).reshape(2,3)
b=np.arange(6).reshape(2,3)
np.hstack([a,b])

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [56]:
a=np.arange(6).reshape(2,3)
b=np.arange(3)
np.vstack([a,b])

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2]])

### Linear Algebra

In [57]:
np.linalg.det(np.eye(2))

1.0

In [59]:
np.linalg.det(np.array([[1,2],[5,7]]))

-2.999999999999999

In [60]:
np.linalg.inv(np.array([[1,2],[5,7]]))

array([[-2.33333333,  0.66666667],
       [ 1.66666667, -0.33333333]])

In [61]:
np.linalg.matrix_rank(np.array([[1,2],[5,7]]))

2

- np.dot
- np.matmul

In [64]:
k=[[1,2],[3,4]]
p=[[6,5],[7,8]]
np.matmul(k,p)

array([[20, 21],
       [46, 47]])

In [66]:
k=[[1,2],[3,4]]
p=[[6,5],[7,8]]
np.matmul(p,k)

array([[21, 32],
       [31, 46]])

In [67]:
k=[[1,2],[3,4]]
p=[[6,5],[7,8]]
np.dot(k,p)

array([[20, 21],
       [46, 47]])

In [20]:
import datetime
f=open('data.txt')
data=f.read()
data=eval(data)
data

[{'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 520},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 521},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 523},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 524},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 530},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 531},
 {'attendance': 'A',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 533},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 534},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
 

In [1]:
import datetime
f=open("data.txt")
s=f.read()
l=eval(s)
print(type(l))
s=set()
s1=set()
for i in l:
    s.add(i['student_id'])
    s1.add(i['date'])
s1=list(s1)
s1.sort()
d={}
for i in l:
    if(i['date']==s1[0]):
        if(i['student_id'] not in list(d.keys())):
            d[i['student_id']]=list()
            d[i['student_id']].append(i['attendance'])
        else:
            d[i['student_id']].append(i['attendance'])
    if(i['date']==s1[1]):
        if(i['student_id'] not in list(d.keys())):
            d[i['student_id']]=list()
            d[i['student_id']].append(i['attendance'])
        else:
            d[i['student_id']].append(i['attendance'])
    if(i['date']==s1[2]):
        if(i['student_id'] not in list(d.keys())):
            d[i['student_id']]=list()
            d[i['student_id']].append(i['attendance'])
        else:
            d[i['student_id']].append(i['attendance'])
for i in d.keys():
    if(len(d[i])<6):
        d[i].insert(2,"NA")
    print(d[i])

<class 'list'>
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['A', 'A', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['A', 'A', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'A', 'A']
['P', 'P', 'A', 'A', 'A', 'A']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'A', 'A']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P'

In [6]:
import re
reg = '^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$'
def check(email):  
    if(re.search(reg,email)):  
        print("Valid Email")            
    else:  
        print("Invalid Email")  
       
email = input("enter the Email Id: ")
check(email)

enter the Email Id: tvnagajyothi@gmail.com
Valid Email


In [11]:
import re
reg = '\\w{3}\\w{3}\\w{4}'
def check(phone):  
    if(re.search(reg,phone)):  
        print("Valid Phone number")            
    else:  
        print("Invalid Phone number")  
       
phone = input("enter the Phone number: ")
check(phone)

enter the Phone number: 9100550480
Valid Phone number
